### ISSUE TITLE
a little suggestion for styles

### ISSUE THREAD

**Issue by gera2ld** [zenorocha/jquery-github#42]
The box looks strange on pages with CSS resets like this:
``` css
* { box-sizing: border-box; }
```
This is used quite often as far as I know.
So I suggest this to be added to `base.css`:
``` css
.github-box .github-box-download {
  // ...
  box-sizing: content-box;
}
```
